name: Update OHLCV

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ambil data TRUK
        env:
          API_KEY: ${{ secrets.IDX_EDGE_API_KEY }}
        run: |
          mkdir -p data

          curl -L \
            -H "X-API-Key: $API_KEY" \
            -H "Accept: application/json" \
            "https://stock.arjum.com/api/history/TRUK" \
            -o data/truk_history.json

      - name: Cek hasil
        run: |
          echo "=== HASIL API TRUK ==="
          cat data/truk_history.json
